name: Dynamic Tests on Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  test:

    services:
      postgres:
        image: postgres:11.18-bullseye
        env:
          POSTGRES_USER: decide
          POSTGRES_PASSWORD: decide
          POSTGRES_DB: decide
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Apply Migrations
      run: | 
        cd decide
        python manage.py migrate

    - name: Install jq
      run: sudo apt-get install jq -y

    - name: Get Labels
      run: |
        labels_response=$(curl -s "https://api.github.com/repos/nicoloboo02/decide/pulls/${{ github.event.number }}/labels")
        echo "Labels response: $labels_response"
        labels=$(echo $labels_response | jq -r '.[].name')
        echo "Extracted labels: $labels"

    - name: Run Tests based on Labels
      run: |
        labels=$(curl -s "https://api.github.com/repos/nicoloboo02/decide/pulls/${{ github.event.number }}/labels" | jq -r '.[].name')
        
        for label in $labels; do
          echo "Running tests for module: $label"
          cd decide 
          python manage.py test $label
        done
