name: Dynamic tests

on:
  issue_comment:
    types:
      - created

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Apply Migrations
      run:  |
        cd decide
        python manage.py migrate

    - name: Check for Label Comment
      run: |
        comment=$(cat $GITHUB_EVENT_PATH | jq -r '.comment.body')
        labels=$(curl -s "https://api.github.com/repos/nicoloboo02/decide/pulls/${{ github.event.number }}/labels" | jq -r '.[].name')

        if [[ "$comment" == *"Labels añadidas"* ]]; then
          for label in $labels; do
            echo "Running tests for module: $label"
            cd decide
            python manage.py test $label
          done
        else
          echo "No 'Labels añadidas' comment found. Skipping tests."
        fi

